/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author User
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        MenuCadHospede = new javax.swing.JMenuItem();
        MenuConHospede = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        MenuCadQuarto = new javax.swing.JMenuItem();
        MenuConQuarto = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        MenuCadFuncionarios = new javax.swing.JMenuItem();
        MenuConFuncionarios = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        MenuCadFornecedores = new javax.swing.JMenuItem();
        MenuConFornecedores = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        MenuCadProdutos = new javax.swing.JMenuItem();
        MenuConProdutos = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        MenuCadServicos = new javax.swing.JMenuItem();
        MenuConServicos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Cadastro   |");

        jMenu9.setText("Hóspede");

        MenuCadHospede.setText("Cadastrar");
        jMenu9.add(MenuCadHospede);

        MenuConHospede.setText("Consultar");
        jMenu9.add(MenuConHospede);

        jMenu1.add(jMenu9);

        jMenu10.setText("Quarto");

        MenuCadQuarto.setText("Cadastrar");
        jMenu10.add(MenuCadQuarto);

        MenuConQuarto.setText("Consultar");
        jMenu10.add(MenuConQuarto);

        jMenu1.add(jMenu10);

        jMenu11.setText("Funcionários");

        MenuCadFuncionarios.setText("Cadastrar");
        jMenu11.add(MenuCadFuncionarios);

        MenuConFuncionarios.setText("Consultar");
        jMenu11.add(MenuConFuncionarios);

        jMenu1.add(jMenu11);

        jMenu12.setText("Fornecedores");

        MenuCadFornecedores.setText("Cadastrar");
        jMenu12.add(MenuCadFornecedores);

        MenuConFornecedores.setText("Consultar");
        jMenu12.add(MenuConFornecedores);

        jMenu1.add(jMenu12);

        jMenu13.setText("Produtos");

        MenuCadProdutos.setText("Cadastrar");
        jMenu13.add(MenuCadProdutos);

        MenuConProdutos.setText("Consultar");
        jMenu13.add(MenuConProdutos);

        jMenu1.add(jMenu13);

        jMenu14.setText("Serviços");

        MenuCadServicos.setText("Cadastrar");
        jMenu14.add(MenuCadServicos);

        MenuConServicos.setText("Consultar");
        jMenu14.add(MenuConServicos);

        jMenu1.add(jMenu14);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Reservas   |");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Vendas");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Financeiro   |");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Relatórios   |");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Segurança   |");
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Ferramentas   |");
        jMenuBar1.add(jMenu7);

        jMenu8.setText("Sair");
        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 677, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuCadFornecedores;
    private javax.swing.JMenuItem MenuCadFuncionarios;
    private javax.swing.JMenuItem MenuCadHospede;
    private javax.swing.JMenuItem MenuCadProdutos;
    private javax.swing.JMenuItem MenuCadQuarto;
    private javax.swing.JMenuItem MenuCadServicos;
    private javax.swing.JMenuItem MenuConFornecedores;
    private javax.swing.JMenuItem MenuConFuncionarios;
    private javax.swing.JMenuItem MenuConHospede;
    private javax.swing.JMenuItem MenuConProdutos;
    private javax.swing.JMenuItem MenuConQuarto;
    private javax.swing.JMenuItem MenuConServicos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
